name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]

jobs:

  build:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        go: ["1.19.x", "1.20.x"]
        include:
        - go: 1.20.x
          lint: true

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}
        cache: true

    - name: Lint
      run: make lint
      if: matrix.lint

    - name: Test
      run: make cover
      shell: bash

    - name: Upload coverage
      uses: codecov/codecov-action@v3
