name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]

jobs:

  build:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        go: ["1.19.x", "1.20.x"]
        include:
        - go: 1.20.x
          lint: true

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}
        cache: true

    - name: Lint
      run: make lint
      if: matrix.lint

    - name: Test
      run: make cover
      shell: bash

    - name: Upload coverage
      uses: codecov/codecov-action@v3

  docs:
    name: Update documentation
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: abhinav/stitchmd-action@v1
      with:
        mode: ${{ github.event_name == 'pull_request' && 'write' || 'check' }}
        summary: doc/README.md
        output: README.md
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        file_pattern: doc/README.md
        commit_message: 'Auto-update README.md with stitchmd'
